"""Add is_available to Song and tidal_id to Playlist

Revision ID: 3e68da44fa7f
Revises: cad9268f77e7
Create Date: 2025-11-30 00:58:30.406962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3e68da44fa7f'
down_revision: Union[str, Sequence[str], None] = 'cad9268f77e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('tidal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_playlist_tidal_id'), 'playlist', ['tidal_id'], unique=False)
    op.add_column('song', sa.Column('is_available', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'is_available')
    op.drop_index(op.f('ix_playlist_tidal_id'), table_name='playlist')
    op.drop_column('playlist', 'tidal_id')
    # ### end Alembic commands ###
