"""Add last_synced_at to Playlist

Revision ID: ab5abdcff5ee
Revises: e4faf38d397b
Create Date: 2025-11-30 22:18:45.622620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ab5abdcff5ee'
down_revision: Union[str, Sequence[str], None] = 'e4faf38d397b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist', 'last_synced_at')
    # ### end Alembic commands ###
