"""add_token_type_and_change_name_expires_at_to_expiry_time_to_tidaltoken

Revision ID: e4faf38d397b
Revises: 3e68da44fa7f
Create Date: 2025-11-30 18:04:50.149521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e4faf38d397b'
down_revision: Union[str, Sequence[str], None] = '3e68da44fa7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tidaltoken', sa.Column('token_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('tidaltoken', sa.Column('expiry_time', sa.DateTime(), nullable=False))
    op.drop_column('tidaltoken', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tidaltoken', sa.Column('expires_at', sa.DATETIME(), nullable=False))
    op.drop_column('tidaltoken', 'expiry_time')
    op.drop_column('tidaltoken', 'token_type')
    # ### end Alembic commands ###
